---
- hosts: all
  become: yes

  vars_prompt:
    - name: "user_name"
      prompt: "What is user name?"
      private: no

    - name: "user_password"
      prompt: "What is user password?"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes

    - name: "user_groups"
      prompt: "What is user groups?"
      private: no
      default: ""

    - name: "authorized_key"
      prompt: 'Path to authorized key file? (Type "no" to skiped)'
      private: no
      default: "~/.ssh/id_rsa.pub"

  tasks:

    - name: Create user
      user: 
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        update_password: on_create
        shell: /bin/bash
        groups: "{{ user_groups }}"
        append: yes

    - name: Set authorized key took from file
      authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "{{ lookup('file', '{{ authorized_key }}') }}"
      when: authorized_key != "n" and authorized_key != "no"
